--- 
title: "Khóa học Data Science"
author: "Lê Huỳnh Đức"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
description: "Khóa học Data Science"
---

<!--chapter:end:index.Rmd-->

# Phân tích dữ liệu chuỗi thời gian {-}

## Tuần 1: Giới thiệu cơ bản về Dữ liệu chuỗi thời gian {-}

- Giới thiệu chuỗi thời gian
    - Chuỗi thời gian là gì
    - Luyện tập chuỗi thời gian trên Pandas và Numpy
- Phân rã các thành phần dữ liệu chuỗi thời gian
    - Các thành phần chuỗi thời gian
        - Xu hướng
        - Thời vụ
        - Chu kì
    - Mô hình phân rã các thành phần thời gian
        - Mô hình cộng
        - Mô hình nhân
    - Luyện tập phân rã chuỗi thời gian
- Các bác toán về chuỗi thời gian
    - Phân tích các thành phần chuỗi thời gian
    - Dự báo chuỗi thời gian
    - Phân loại chuỗi thời gian
    - Phân đoạn chuỗi thời gian

## Tuần 2: ARIMA model {-}

- Tính dừng và Làm mịn chuỗi thời gian
    - Tính dừng là gì
    - Làm mịn chuỗi thời gian
        - Phương pháp Moving Average
        - Phương pháp Exponential Smoothing
        - Phương pháp Whittaker-Eilers Smoothing
- ARIMA Model
    - Lag là gì
    - Tự tương quan là gì
    - Autoregressive model
    - Moving Average process
    - ARMA, ARIMA
- Sử dụng ARIMA bằng Python

## Tuần 3: VAR model, ARCH model, Hierachical  {-}

- Phân tích dữ liệu chuỗi thời gian đa biến 
- Các mô hình phương sai có điều kiện
- Dữ liệu chuỗi thời gian dạng thứ bậc


## Tuần 4: Mô hình cây và Deep Learning  {-}

- Mô hình cây trong Dự đoán chuỗi thời gian
- Deep Learning trong Dự đoán chuỗi thời gian


## Tuần 5: Mô hình phân tích Sống Sót (Survival Analysis) {-}

## Tuần 6: Anomaly Detection {-}

## Tuần 7: Sử dụng một số thư viện Forecasting {-}

- TSLearn
- MLForeacasting
- Prophet

<!--chapter:end:posts/01-TimeSeries.rmd-->

# Triển khai Machine Learning

## Tuần 1: mlflow {-}

- Giới thiệu mlflow
    - mlflow là gì
    - hướng dẫn cài đặt mlflow
- Tracking trong mlflow
    -  Các thành phần trong tracking
        - parameters
        - metrics
        - artifacts
        - source code
    - Các bước thực hiện cơ bản
        - Thiết lập thí nghiệm
        - Huấn luyện mô hình và lưu các tham số
        - Truy vấn các thí nghiệm
    - So sánh các thí nghiệm với nhau
- Quản lý các phiên bản mô hình và triển khai sản phẩm
    - Quản lý các phiên bản mô hình
    - Triển khai mô hình

    
## Tuần 2: airlfow {-}

- Giới thiệu airflow
    - Airflow là gì
    - Các khái niệm trong airflow
        - Task
        - Task instance
        - DAG
        - DAG run
    - Các thành phần trong airflow
        - Web server
        - Scheduler
        - Executor
        - Metadata database
    - Hướng dẫn cài đặt airflow

<!--chapter:end:posts/02-Development.rmd-->

