# Triển khai Machine Learning {-}

## Tuần 1: mlflow {-}

- Giới thiệu mlflow
    - mlflow là gì
    - hướng dẫn cài đặt mlflow
- Tracking trong mlflow
    -  Các thành phần trong tracking
        - parameters
        - metrics
        - artifacts
        - source code
    - Các bước thực hiện cơ bản
        - Thiết lập thí nghiệm
        - Huấn luyện mô hình và lưu các tham số
        - Truy vấn các thí nghiệm
    - So sánh các thí nghiệm với nhau
- Quản lý các phiên bản mô hình và triển khai sản phẩm
    - Quản lý các phiên bản mô hình
    - Triển khai mô hình

    
## Tuần 2: airlfow {-}

- Giới thiệu airflow
    - Airflow là gì
    - Các khái niệm trong airflow
        - Task
        - Task instance
        - DAG
        - DAG run
    - Các thành phần trong airflow
        - Web server
        - Scheduler
        - Executor
        - Metadata database
    - Hướng dẫn cài đặt airflow

- Hướng dẫn viết DAG cho Datapipeline
    - lập lịch xử lý dữ liệu
    - lập lịch huấn luyện mô hình
    - lập lịch suy luận mô hình offline
    - lập lịch monitor kết quả mô hình

## Tuần 3: Triển khai mô hình dạng Webservice với FastAPI {-}

- Giới thiệu FastAPI là gì
- Triển khai Machine Learning Service bằng FastAPI và Pydantic

## Tuần 4: Docker {-}

